routes.py
from flask import Blueprint, request
from views import show_register, register, login, check_login, home, homePage, show_login_form,\
    show_searchByDate_form, searchByDate, show_searchByMonth_form, searchByMonth,display_activity,\
    show_searchByYear_form, default, logout, activity, get_calendar, switch_month, searchPage, get_more_posts, \
    show_edit_page, search_activities_for_editing, merge_check, merge_activities, unmerge_check, unmerge_activity

bp = Blueprint('main', __name__)

def login_required(f):
    return check_login(f)

@bp.route('/registrationPage')
def show_register_route():
    return show_register()

@bp.route('/register', methods=['POST'])
def register_route():
    firstname = request.form['first-name']
    lastname = request.form['last-name']
    email = request.form['email']
    username = request.form['username']
    password = request.form['password']
    return register(firstname, lastname, email, username, password)

@bp.route('/login', methods=['POST'])
def login_route():
    username = request.form['username']
    password = request.form['password']
    return login(username, password)

@bp.route('/login_form', methods=['GET'])
def show_login_form_route():
    login_error = request.args.get('show_error')
    print(f'LOGIN ERROR: {login_error}')
    return show_login_form(login_error)

@bp.route('/', methods=['GET'])
@login_required
def homePage_route():
    return homePage()

@bp.route('/filter_posts', methods=['GET'])
@login_required
def filter_posts_route():
    sport = request.args.get('sport')
    return get_more_posts(0, 15, sport)

@bp.route('/load_more', methods=['GET'])
@login_required
def load_more_route():
    offset = request.args.get('offset')
    sport = request.args.get('sport')
    return get_more_posts(offset, 10, sport)

@bp.route('/searchPage', methods=['GET'])
@login_required
def searchPage_route():
    return searchPage()

@bp.route('/searchByDate', methods=['GET'])
@login_required
def show_searchByDate_form_route():
    return show_searchByDate_form()

@bp.route('/multiple_activity', methods=['GET'])
@login_required
def searchByDate_route():
    date = request.args.get('date1')
    date2 = request.args.get('date2')
    print(f'DATE1: {date}, DATE2: {date2}')
    if date2: 
        return searchByMonth(date, date2)#(month and year)
    return searchByDate(date)#(single date)

@bp.route('/searchByMonth', methods=['GET'])
@login_required
def show_searchByMonth_form_route():
    return show_searchByMonth_form()

@bp.route('/ByMonth', methods=['GET'])
@login_required
def searchByMonth_route():
    month = request.args.get('month')
    year = request.args.get('year')
    return searchByMonth(month, year)

@bp.route('/searchByYear_form', methods=['GET'])
@login_required
def show_searchByYear_form_route():
    return show_searchByYear_form()

@bp.route('/default', methods=['GET'])
@login_required
def default_route():
    return default()

@bp.route('/logout', methods=['GET'])
def logout_route():
    return logout()

@bp.route('/activity/<activity_id>')
@login_required
def activity_route(activity_id):
    return activity(activity_id)

@bp.route('/activity', methods=['POST'])
def activity_route_post():
    activity = request.form.get('activity')
    lap_html = request.form.get('lap_html')
    folium_map = request.form.get('folium_map')
    return display_activity(activity, lap_html, folium_map)

@bp.route('/calendar', methods=['GET'])
@login_required
def calendar_route():
    return get_calendar()

@bp.route('/switch_month/<int:year>/<int:month>')
@login_required
def switch_month_route(year, month):
   return switch_month(year, month)

@bp.route('/edit_page', methods=['GET'])
@login_required
def show_edit_page_route():
    return show_edit_page()

@bp.route('/search_activities_for_edit', methods=['GET'])
@login_required
def search_activities_for_edit_route():
    input = request.args.get('input')
    input_type = request.args.get('input_type')
    return search_activities_for_editing(input, input_type)

@bp.route('/merge_check', methods=['POST'])
@login_required
def merge_check_route():
    data = request.get_json()
    activity1 = data.get('activity1')
    activity2 = data.get('activity2')
    return merge_check(activity1, activity2)

@bp.route('/merge_activities', methods=['POST'])
@login_required
def merge_activities_route():
    data = request.get_json()
    activity1 = data.get('activity1')
    activity2 = data.get('activity2')
    return merge_activities(activity1, activity2)

@bp.route('/unmerge_check', methods=['POST'])
@login_required
def unmerge_check_route():
    data = request.get_json()
    merged_activity_id = data.get('activity_id')
    return unmerge_check(merged_activity_id)

@bp.route('/unmerge_activity', methods=['POST'])
@login_required
def unmerge_activity_route():
    data = request.get_json()
    merge_id = data.get('merge_id')
    print(f'MERGE ID: {merge_id}')
    return unmerge_activity(merge_id)

templates/_activity.html
<div class="containerMult">
    <div class='header'>
        <div class='topHeader'>
            {% if activity['is_merged'] %}
                <button class='unmerge-btn' onclick='unmergeActivity({{i}})'>Unmerge Activity</button>
            {% endif %}
            {% if activity['sport'] == 'Running' %}
                <img src="../static/images/running-icon.jpg" alt="Running icon">
            {% elif activity['sport'] == 'Cycling' %}
                <img src="../static/images/cycling-icon.png" alt="Running icon">
            {% elif activity['sport'] == 'Rowing' %}
                <img src="../static/images/rowing-icon.jpg" alt="Running icon">
            {% endif %}
            <div>
                <h1><span class="date-name">{{activity['display_date']}}</span></h1>
                <h1><span class="sport-name">{{activity['display_sport']}}</span></h1>
            </div>
        </div>
        <h1><button onclick="navigateToActivity({{i}})" class="titleName">{{activity['activity_title']}}</button></h1>
        <h3><span class = 'name'>Description:</span> <span class = 'value'>{{activity['description']}}</span></h3>
    </div>
    <div class='times'>
        <div class='grid-container2'>
            <h2><span class="name">Duration:</span> <span class="value">{{activity['total_time']}}</span></h2>
            <h2><span class="name">Elapsed Time:</span> <span class="value">{{activity['total_elapsed_time']}}</span></h2>
            {% if activity['sport'] == 'Running'%}                
                <h2><span class="name">Avg Pace:</span> <span class="value">{{activity['pace']}} /mi</span></h2>
                <h2><span class="name">Elapsed Pace:</span> <span class="value">{{activity['elapsed_pace']}} /mi</span></h2>
            {% elif activity['sport'] == 'Cycling'%}
                <h2><span class="name">Avg Speed:</span> <span class="value">{{activity['pace']}} mph</span></h2>
                <h2><span class="name">Elapsed Speed:</span> <span class="value">{{activity['elapsed_pace']}} mph</span></h2>
            {% elif activity['sport'] == 'Rowing'%}
                <h2><span class="name">Pace:</span> <span class="value">{{activity['pace']}} /500m</span></h2>
                <h2><span class="name">Elapsed Pace:</span> <span class="value">{{activity['elapsed_pace']}} /500m</span></h2>
            {% endif %}
            {% if activity['sport'] in ('Running', 'Cycling')%}
                <h2><span class="name">Distance:</span> <span class="value">{{activity['total_distance']}} miles</span></h2>
            {% elif activity['sport'] == 'Rowing' %}
                <h2><span class="name">Distance:</span> <span class="value">{{activity['total_distance']}} m</span></h2>
            {% endif %}
        </div>
    </div>
    <div id="map-container" style="width: 100%; height: 45%; margin: 0 auto;">
        {% if folium_map is not none %}
            {{folium_map|safe}}
        {% endif %}
    </div>
    <h1><span class="name">Splits</span></h1>
    <button type="button" onclick="toggleCollapse('splits', this, ' Splits', 'editicon2')" class='splits-button'>View Splits</button>
    {% if lap_html is none %}
        <div class='splits' style="display:none; height:42px">
            <h2>No Split Data to Show</h2>
    {% else %}
        <div class='splits' style="display:none">
            {{lap_html|safe}}
    {% endif %}
    </div>
    <h1><span class="name">Stats</span></h1>
    <button type="button" onclick="toggleCollapse('grid-container', this, ' Stats', null)" class='stats-button'>Hide</button>
    <div class="grid-container">
        <div class='hr'>
            <h2><span class="container-title">Heart Rate:</span></h2>
            <h2><span class="name">Avg HR:</span> <span class="value">{{activity['avg_hr']}} bpm</span></h2>
            <h2><span class="name">Max HR:</span> <span class="value">{{activity['max_hr']}} bpm</span></h2>
            <h2><span class="name">Recovery HR:</span> <span class="value">{{activity['recovery_hr']}} bpm</span></h2>
        </div>
        {% if activity['sport'] == 'Running' %}
            <div class='steps'>
                <h2><span class="container-title">Steps:</span></h2>
                <h2><span class="name">Avg Cadence:</span> <span class="value">{{activity['avg_running_cadence']}} spm</span></h2>
                <h2><span class="name">Max Cadence:</span> <span class="value">{{activity['max_running_cadence']}} spm</span></h2>
                <h2><span class="name">Number of Steps:</span> <span class="value">{{activity['total_strides']}}</span></h2>
                <h2><span class="name">Avg Stride Length:</span> <span class="value">{{activity['avg_stride_length']}} m</span></h2>
            </div>
        {% elif activity['sport'] == 'Rowing' %}
            <div class='strokes'>
                <h2><span class="container-title">Strokes:</span></h2>
                <h2><span class="name">Stroke Rate:</span> <span class="value">{{activity['stroke_rate']}} spm</span></h2>
                <h2><span class="name">Elapsed Stroke Rate:</span> <span class="value">{{activity['elapsed_stroke_rate']}} spm</span></h2>
                <h2><span class="name">Number of Strokes:</span> <span class="value">{{activity['total_cycles']}}</span></h2>
            </div>
        {% endif %}
        <div class='calories'>
            <h2><span class="container-title">Nutrition:</span></h2>
            <h2><span class="name">Resting Calories:</span> <span class="value">{{activity['resting_calories']}} cal</span></h2>
            <h2><span class="name">Active Calories:</span> <span class="value">{{activity['active_calories']}} cal</span></h2>
            <h2><span class="name">Total Calories:</span> <span class="value">{{activity['total_calories']}} cal</span></h2>
            <h2><span class="name">Sweat Loss:</span> <span class="value">{{activity['sweat_loss']}} ml</span></h2>
        </div>
        <div class='elevation'>
            <h2><span class="container-title">Elevation:</span></h2>
            <h2><span class="name">Total Ascent:</span> <span class="value">{{activity['total_ascent']}} ft</span></h2>
            <h2><span class="name">Total Descent:</span> <span class="value">{{activity['total_descent']}} ft</span></h2>
        </div>
    </div>
</div>

templates/_mergeActivities.html
<link rel="stylesheet" type="text/css" href="../static/css/multipleActivity.css">
<div id='mergeConfirmation' class="modal-backdrop" style='display:none;'>
    <div class="merge-confirmation">
        <h1>Are you sure you want to merge these activities?</h1>
        <h2></h2>
        <button onclick='open_merge_modal()'>Yes, Merge Activities</button>
        <button onclick='closeMergeConfirmation()'>No, Cancel</button>
    </div>
</div>
<div id='mergeSuccess' class="modal-backdrop" style='display:none;'>
    <div class="merge-success">
        <input type='hidden' id='merged_activity_id' value=''>
        <h1>Activities Merged Successfully</h1>
        <h2>What would you like to do next?</h2>
        <button onclick='navigate_to_activity()'>View Merged Activity</button>
        <button onclick='navigate_to_home()'>Return to the Home Page</button>
        <button onclick='full_reload_page()'>Continue Editing Activities</button>
    </div>
</div>
<div id='mergeActivities' class='modal-backdrop' style='display:none;'>
    <div class='loading2' style='display:none;'>
        <div>
            <h1>Loading</h1>
        </div>
    </div>
    <div class='merge-activities'>
        <h1 class='merge-title'>Merge Activities</h1>
        <div id='merge-activity1' class='merge-activity'>
            <h2>Activity 1</h2>
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Activity Title</th>
                        <th>Description</th>
                        <th>Date</th>
                        <th>Sport</th>
                        <th>Time</th>
                        <th>Distance</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <div class='swap-merge-activities'>
            <div class='swap-merge-activities-button' onclick='swapActivities()'>
                <svg
                    width="50"
                    height="50"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <path d="M12 16H13.5L13.5 10H15.5L15.5 16H17L14.5 19L12 16Z" fill="currentColor" />
                    <path d="M8 8H9.5L9.5 14H11.5L11.5 8H13L10.5 5L8 8Z" fill="currentColor" />
                </svg>
            </div>
        </div>
        <div id='merge-activity2' class='merge-activity'>
            <h2>Activity 2</h2>
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Activity Title</th>
                        <th>Description</th>
                        <th>Date</th>
                        <th>Sport</th>
                        <th>Time</th>
                        <th>Distance</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
        <button onclick='merge_activities()'>Merge Activities</button>
        <button onclick='closeMergeActivities()'>Cancel</button>
    </div>
</div>

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}GarminMock{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/multipleActivity.css') }}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
    <nav class = "menuBar">
        <img src="{{ url_for('static', filename='images/logo_plain.png') }}" alt="logo" style="width:25px; height:30px;">
        <img src="{{ url_for('static', filename='images/logo_word_menu.png') }}" alt="logo" style="width:100px; height:30px;">
        <nav class = "links">
            <a href = "{{ url_for('main.homePage_route') }}">Home</a>
            <a href = "{{ url_for('main.searchPage_route') }}">Search</a>
            <a href = "{{ url_for('main.show_edit_page_route') }}">Edit</a>
            <a href = "{{ url_for('main.calendar_route') }}">Calendar</a>
            <a href = "{{ url_for('main.default_route') }}">Profile</a>
        </nav>
        <a class = "logout" href = "{{ url_for('main.logout_route') }}">Log Out</a>
    </nav>
{% block body %}
    <div class = "notFound">
        <h1> The page you are looking for was not found or in development. </h1>
    </div>

{% endblock %}
</body>
</html>

templates/calendar.html
{% extends 'base.html' %}
{% block title %}Activities{% endblock %}
        {% block head %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/calendar.css') }}">
        {% endblock %}
{% block body %}
    <h1>Calendar</h1>
    
    <h2 class = "calendarTitle">{{ calendar_title }}</h2>

    <a href="{{ url_for('main.switch_month_route', year=year, month=month-1) }}">Previous Month</a>
    {% if calendar_title != current_month%}
        <a href="{{ url_for('main.switch_month_route', year=year, month=month+1) }}">Next Month</a>
    {% endif %}
    <div class = "calendar">
        <table>
            <tr>
                <th class='day-name'>Sun</th>
                <th class='day-name'>Mon</th>
                <th class='day-name'>Tue</th>
                <th class='day-name'>Wed</th>
                <th class='day-name'>Thu</th>
                <th class='day-name'>Fri</th>
                <th class='day-name'>Sat</th>
            </tr>
            {% for week in calendar %}
            <tr>
                {% for (day, activities) in week %}
                <td class='date-cell'>
                    <h3 class='day'>{{ day }}</h3>
                    {% for activity in activities %}
                        <a class = "activity_link" href="{{url_for('main.activity_route', activity_id=activity['activity_id'])}}">
                            {% if activity['sport'] == 'Running'%}
                            <div class='activity_running'>
                            {% elif activity['sport'] == 'Cycling' %}
                            <div class='activity_cycling'>
                            {% elif activity['sport'] == 'Rowing' %}
                            <div class='activity_rowing'>
                            {% else %}
                            <div class='activity_other'>
                            {% endif %}
                                <h3 class='activ_text'> {{activity['display_sport']}} - {{ activity['activity_title'] }} </h3>
                                <h3 class='activ_text'> <span class="distance">{{ activity['total_distance'] }} miles</span> <span class="time">{{ activity['duration'] }}</span> </h3>                    
                            </div>
                        </a>
                    {% endfor %}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/editPage.html
{% extends 'base.html' %}
{% block title %}Edit{% endblock %}
{% block head %}
    <script src="{{ url_for('static', filename='js/editPage.js') }}"></script>
    <script>
        window.onload = function() {
            // save the state of the modal
            if (localStorage.getItem('mergeModalDisplayed') === 'true') {
                activity1 = JSON.parse(localStorage.getItem('activity1'));
                activity2 = JSON.parse(localStorage.getItem('activity2'));
                open_merge_modal();
            }
        };

        window.onbeforeunload = function() {
            localStorage.clear();
        };
    </script>
{% endblock %}
{% block body %}
    {% include '_mergeActivities.html' %}
    <div id='search-container' class="search-container2">
        <div class="search-form" id='edit-activity-div'>
            <h1>Search Activities</h1>
            <div class='search-options'>
                <button class='active' onclick="show_search_inputs('date', 'edit-activity-div', this)">Search by Date</button>
                <button onclick="show_search_inputs('title', 'edit-activity-div', this)">Search by Activity Title</button>
            </div>
            <form method="get" action="/search_activities_for_edit">
                <input type="date" name="date" placeholder="Date" required>
                <input type="text" name="title" placeholder="Activity Title" style='display:none;'>
                <button onclick="search_activities(this.parentElement, event)" name="search">Search</button>
            </form>
        </div>
        <div id='search-results' class="search-results-container" style="display: none;">
            <div class="edit-options">
                <button 
                    id='edit-option-edit' 
                    style='opacity: 50%; pointer-events: none;'
                    disabled
                >Edit Activity</button>
                <button 
                    id='edit-option-merge' 
                    style='opacity: 50%; pointer-events: none;' 
                    onclick="merge_check()"
                    disabled
                >Merge Activities</button>
                <button 
                    id='edit-option-delete' 
                    style='opacity: 50%; pointer-events: none;' 
                    disabled
                >Delete Activities</button>
            </div>
            <div class="search-results">
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th>Activity Title</th>
                            <th>Description</th>
                            <th>Date</th>
                            <th>Sport</th>
                            <th>Time</th>
                            <th>Distance</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/error.html
<!DOCTYPE html>
<html>
<head>
    <title>Error</title>
</head>
<body>
    <h1>Error</h1>
    {% if (service_method) %}
        <p> Service method: {{ service_method }}</p>
    {% endif %}
    {% if (prod_error) %}
        <p> {{ prod_error }}</p>
    {% endif %}
    <p>{{ error_message }}</p>
    <a href="/">Return to the homepage</a>
</html>

templates/homePage.html
{% extends "base.html" %}
    
{% block title %}Home{% endblock %}
{% block head %}
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
{% endblock %}
{% block body %}
    <div class="home_body">
        <div class="card">
            <h1 class="home_h1">Home</h1>
            <a class="home_link" href="{{ url_for('main.show_searchByDate_form_route') }}" class="search_by_date">Search By Date</a>
            <a class="home_link" href="{{ url_for('main.show_searchByMonth_form_route') }}" class="search_by_month">Search By Month</a>
            <a class="home_link" href="{{ url_for('main.show_searchByDate_form_route') }}" class="search_by_year">Search By Year</a>
        </div>
    </div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Log In</title>
        <link rel="stylesheet" type="text/css" href="../static/css/multipleActivity.css">
    </head>
    <body class = loginPage>
        <div class="logo-container">
            <img src="../static/images/logo.png" alt="logo" class="logo">
        </div>
        <div class="loginContainer">
            <form method="post" action="/login">
                {% if show_error %}
                    <h5 style="color:red"> The username or password is incorrect. </h5>
                {% endif %}
                <div class='button-container'>
                    <h1>Log In</h1>
                </div>
                <div>
                    <input type="text" class = 'loginInput' placeholder="Username" name="username" required>
                </div>
                <div>
                    <input type="password" class = 'loginInput' placeholder="Password" name="password" required>
                </div>
                <div class="button-container">
                    <button class = 'submitButton' type="submit">Submit</button>
                </div>
            </form>
        </div>
        <div class="account-container">
            <h5>Don't have an account?</h5>
            <a href="{{ url_for('main.show_register_route') }}" class="create-account-link">Create Account</a>
        </div>
    </body>
</html>

templates/multipleActivity.html
{% extends 'base.html' %}
        {% block title %}Activities{% endblock %}
        {% block head %}
            <script src="{{ url_for('static', filename='js/multipleActivity.js') }}"></script>
            <script>
                const activities = {{ activity_list|tojson }};
                const lap_htmls = {{lap_html_list|tojson}};
                const maps = {{folium_maps|tojson}};

                let loadMoreEnabled = '{{enable_load_more}}' === 'True';

            </script>
        {% endblock %}
{% block body %}
    <form action = '/activity' method = 'POST' id="activity-form" hidden>
        <input type = 'hidden' name = 'activity' id = 'activity-input'>
        <input type = 'hidden' name = 'lap_html' id = 'lap-input'>
        <input type = 'hidden' name = 'folium_map' id = 'map-input'>
    </form>
    {% include '_unMergeActivities.html' %}
    <div id = 'modalBackdrop' class = 'modal-backdrop' style='display:none;'></div>
    {% if date_title %}
        <h1 class ='pageTitle'>Activities for {{date_title}}</h1>
    {% endif %}
    {% if enable_load_more %}
        <div class="filters" id='filter-button-container'>
            <button id='Running_filter' class="filter-button" onclick="filterPosts('Running')">Running</button>
            <button id='Cycling_filter' class="filter-button" onclick="filterPosts('Cycling')">Cycling</button>
            <button id='Rowing_filter' class="filter-button" onclick="filterPosts('Rowing')">Rowing</button>
            <button id='Other_filter' class="filter-button" onclick="filterPosts('Other')">Other</button>
        </div>
    {% endif %}
    <div id='posts-container' class='{{"posts-container-filter" if enable_load_more else "posts-container"}}'>
        {% for activity, lap_html, folium_map, i in zip(activity_list, lap_html_list, folium_maps, list(range(len(activity_list)))) %}
            {% include "_activity.html" with context %}
        {% endfor %}
    </div>    
    <div id="loading" class='loading' style="display: none;">Loading...</div>
{% endblock %}

templates/registration.html
<!DOCTYPE html>
<html>
    <head>
        <title>Create Account</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                padding: 20px;
            }

            .box {
                background-color: white;
                padding: 20px;
                border-radius: 5px;
                box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.1);
                max-width: 500px;
                margin: auto;
            }

            h1 {
                text-align: center;
                color: #333;
            }

            h5 {
                margin-bottom: 5px;
            }

            input {
                width: 100%;
                padding: 10px;
                border: 1px solid #ddd;
                border-radius: 5px;
                margin-bottom: 20px;
            }

            .create-account-button {
                width: 100%;
                background-color: #4CAF50;
                color: white;
                padding: 15px 20px;
                margin: 10px 0;
                border: none;
                border-radius: 5px;
                cursor: pointer;
                font-size: 18px;
            }

            .create-account-button:hover {
                background-color: #45a049;
            }
            .checkmark {
                font-size: 20px;
            }
    
            .checkmark.green {
                color: green;
            }
    
            .checkmark.red {
                color: red;
            }
        </style>
    </head>
    <body>
        <div>
            <h1>Create Account</h1>
            <div class="box">
                <form action="/registrationPage" method="post">
                    <div>
                        <h5>First Name</h5>
                        <input type="text" id="first-name" name = 'first-name' placeholder="First Name">
                    </div>
                    <div>
                        <h5>Last Name</h5>
                        <input type="text" id="last-name" name = 'last-name' placeholder="Last Name">
                    </div>
                    <div>
                        <h5>Email</h5>
                        <input type="text" id="email" name = 'email' placeholder="Email">
                    </div>
                    <div>
                        <h5>Username</h5>
                        <input type="text" id="username" name = 'username' placeholder="Username">
                    </div>
                    <div>
                        <h5>Password</h5>
                        <input type="password" id="password" name = 'password' placeholder="Password">
                    </div>
                    <div>
                        <h5>Confirm Password</h5>
                        <input type="password" id="confirm-password" placeholder="Confirm Password">
                        <span id="password-checkmark" class="checkmark"></span>
                        <span id="password-message"></span>
                    </div>
                    <div class="button-container">
                        <button type="submit" class="create-account-button">Create Account</button>
                    </div>
                </form>
            </div>
        </div>
    
        <script>
            document.getElementById('confirm-password').addEventListener('keyup', function() {
                var password = document.getElementById('password').value;
                var confirmPassword = document.getElementById('confirm-password').value;
                var checkmark = document.getElementById('password-checkmark');
                var message = document.getElementById('password-message');
    
                if (password === confirmPassword) {
                    checkmark.innerHTML = '&#10004;'; // Unicode for green checkmark
                    checkmark.className = 'checkmark green';
                    message.textContent = 'Passwords match.';
                    message.style.color = 'black';
                } else {
                    checkmark.innerHTML = '&#10008;'; // Unicode for red checkmark
                    checkmark.className = 'checkmark red';
                    message.textContent = 'Passwords do not match.';
                    message.style.color = 'red';
                }
            });
        </script>
    </body>
</html>
    

templates/searchByDate.html
{% extends "base.html" %}
{% block title %}Search By Date{% endblock %}
{% block body %}
<div class="search-container">
    <h2 class="search-h2">Search for Activity by Date</h2>
    <div class="search-form">
        <form method="get" action="/multiple_activity">
            <input type="date" name="date1" placeholder="Date" required><br><br>
            <button type="submit">Search</button>
        </form>
    </div>
</div>
{% endblock %}

templates/searchPage.html
{% extends "base.html" %}
    
{% block title %}Home{% endblock %}
{% block head %}
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
{% endblock %}
{% block body %}
    <div class="home_body">
        <div class="card">
            <h1 class="home_h1">Home</h1>
            <a class="home_link" href="{{ url_for('main.show_searchByDate_form_route') }}" class="search_by_date">Search By Date</a>
            <a class="home_link" href="{{ url_for('main.show_searchByMonth_form_route') }}" class="search_by_month">Search By Month</a>
            <a class="home_link" href="{{ url_for('main.show_searchByDate_form_route') }}" class="search_by_year">Search By Year</a>
        </div>
    </div>
{% endblock %}